ansible-community/antsibull-changelog

CHANGELOG.rst, antsibull_changelog/cli.py, antsibull_changelog/config.py, antsibull_changelog/fragment.py
Like:
- `changelogs/config.yaml` is not present (better error messages)
- `changelogs/config.yaml` is not a directory, or does not contain `sections`
- `changelogs/fragments` does not exist (or is no directory)
=> Improve behavior in some unexpected situations

CHANGELOG.rst, antsibull_changelog/cli.py, antsibull_changelog/config.py, docs/changelogs.rst, tests/units/test_config.py
Needed for community.general and community.network so we don't have to specify this manually for every antsibull-changelog generate / release call.
=> Add flatmap setting

docs/changelogs.rst
Clarify that changelog fragments aren't needed for properly documented new modules and plugins.
=> Add note : do not need fragments for new plugins

docs/changelog.yaml-format.md
Because changelog.yaml should be YAML 1.1 file, we need to be a bit careful with bare YYYY-MM-DD literals since those are interpreted as dates and thus do not conform to the specification of the changelog file.
=> Fix example with release date

CHANGELOG.rst, antsibull_changelog/plugins.py, tests/functional/test_changelog_basic_ansible.py, tests/functional/test_changelog_basic_ansible_classic.py
Found while working on #55. That one will also contain better tests for this.
=> Fix bug when using namespaces in ansible-base/-core without --use-ansible-doc

CHANGELOG.rst, antsibull_changelog/ansible.py, antsibull_changelog/changes.py, antsibull_changelog/cli.py, antsibull_changelog/plugins.py, tests/functional/fixtures.py, tests/functional/test_changelog_basic_collection.py
Since ansible-core 2.11, ansible-doc allows listing roles with an argument spec, which have documentation per entry points. If such a role has a `main` entrypoint whose documentation contains `version_added`, antsibull-changelog will now consider it for automatically detecting new roles.
=> Support roles with argument spec and `main` entrypoint

CHANGELOG.rst, README.md, antsibull_changelog/changes.py, antsibull_changelog/cli.py, antsibull_changelog/config.py, antsibull_changelog/logger.py, antsibull_changelog/plugins.py, antsibull_changelog/utils.py, changelogs/changelog.yaml, changelogs/config.yaml, changelogs/fragments/other-projects.yml, changelogs/fragments/use_semantic_versioning.yml, docs/changelog-configuration.rst, docs/changelog.yaml-format.md, docs/changelogs.rst, docs/other-projects.rst, tests/functional/fixtures.py, tests/functional/test_changelog_basic_other.py, tests/units/test_config.py
This adds basic support for other projects than ansible-core and Ansible collections. Right now you have to create `changelogs/config.yaml` manually, and make sure that it contains `is_other_project: true`. Besides that, the basic functionality seems to work.
Eventually fixes #59.
=> Support other projects than ansible-core and Ansible collections

antsibull_changelog/cli.py, changelogs/fragments/67-lint-before-release.yml, tests/functional/test_changelog_basic_collection.py, tests/functional/test_changelog_basic_other.py
=> Always lint before releasing

antsibull_changelog/plugins.py
=> Fix strange namespace issues

changelogs/fragments/0.14.0.yml, changelogs/fragments/changelog-linting.yml, pyproject.toml, src/antsibull_changelog/lint.py
Needed to fix broken CI in antsibull (due to beta release).
=> Allow to use packaging.version.Version for linting changelog.yaml files

.github/workflows/changelog-lint.yml, changelogs/fragments/76-lint-changelog-yaml.yml, docs/changelog.yaml-format.md, src/antsibull_changelog/cli.py, src/antsibull_changelog/lint.py, tests/functional/test_changelog_yaml_linter.py
First step to deprecating antsibull-lint; see https://github.com/ansible-community/antsibull/issues/410.
=> Add lint-changelog-yaml command

README.md, changelogs/fragments/80-pyproject-poetry.yml, pyproject.toml, src/antsibull_changelog/cli.py
This simplifies the release process of antsibull-changelog, antsibull-core, antsibull-docs, antsibull, and any other project that uses this changelog generator that's based on Python's poetry, since the `--version` parameter no longer needs to be used.
=> Allow to extract version for Python's poetry based projects

.github/workflows/changelog-lint.yml, .github/workflows/pythontests.yml, pyproject.toml, src/antsibull_changelog/plugins.py, src/antsibull_changelog/rstcheck.py, stubs/rstcheck_core/types.pyi
There's a bug that's unfortunately not caught in the tests since these run with an older rstcheck version. For some reason, poetry insists on installing rstcheck 3.5.0. This is because `poetry update` tries to install versions of the dependency that support **all** Python versions that antsibull-changelog also supports, i.e. 3.6+, and only rstcheck < 4.0.0 does that.
=> Fix rstcheck-core support

changelogs/fragments/103-exceptions.yml, src/antsibull_changelog/cli.py, src/antsibull_changelog/config.py, src/antsibull_changelog/plugins.py, src/antsibull_changelog/toml.py, tests/functional/test_changelog_basic_other.py
Ref: https://github.com/ansible-community/antsibull-changelog/pull/98#discussion_r1096144470
=> Avoid raising raw 'Exception'

changelogs/fragments/105-version-codename.yml, src/antsibull_changelog/cli.py
Improves the situation for #104 a bit.
=> Fix boolean error in warning; error out if only one of `--version` and `--codename` is supplied for an ansible-core release

noxfile.py
When I tried to prepare a release with `nox -e bump -- 0.20.0 "..."`, I got
```
nox > Running session bump
nox > Creating virtual environment (virtualenv) using python in .nox/bump
nox > git status --porcelain=v1 --untracked=normal
nox > python -m pip install antsibull-changelog 'tomli ; python_version < '"'"'3.11'"'"'' -U
nox > python -c 'import yaml ; print(yaml.dump(dict(release_summary='"'"'Bugfix and maintenance release using a new build system.'"'"')))'
nox > git add pyproject.toml changelogs/fragments/0.20.0.yml
nox > git commit -m 'Prepare 0.20.0.'
[main f5b0f03] Prepare 0.20.0.
2 files changed, 6 insertions(+), 1 deletion(-)
create mode 100644 changelogs/fragments/0.20.0.yml
nox > antsibull-changelog release
ERROR: Uncaught exception. Run with -v to see traceback.
nox > Command …
```
=> Truncate file after replacing version

pyproject.toml, tests/functional/test_changelog_archive.py, tests/functional/test_changelog_basic_ansible.py, tests/functional/test_changelog_basic_ansible_classic.py, tests/functional/test_changelog_basic_collection.py, tests/functional/test_changelog_basic_lint.py, tests/functional/test_changelog_basic_other.py
The `mock` package is a backport of unittest.mock. It is not needed for
newer Pythons.
=> tests: use unittest.mock instead of mock

changelogs/fragments/131-generate.yml, src/antsibull_changelog/changelog_generator.py, src/antsibull_changelog/cli.py, tests/functional/test_changelog_basic_collection.py
=> Allow to generate a changelog entry without preamble for a specific version, and write it to a given filename

changelogs/fragments/103-312.yaml
I figured this change could use a changelog fragment.
Relates: https://github.com/ansible-community/antsibull-changelog/pull/134
=> Add changelog entry for Python 3.12 support

noxfile.py, pyproject.toml, src/antsibull_changelog/__init__.py
We did this change to antsibull-docs some time ago. I had to fix that a bit today with https://github.com/ansible-community/antsibull-docs/commit/676780b99912f5e9d8b206b14a65ed03d8405919. This PR applies the noxfile changes to this project as well.
=> Use 'hatch version' instead of manually updating the version

CHANGELOG.md, CHANGELOG.md.license, CHANGELOG.rst, changelogs/config.yaml, changelogs/fragments/139-output-formats.yml, docs/changelog-configuration.rst, noxfile.py, src/antsibull_changelog/changelog_generator.py, src/antsibull_changelog/cli.py, src/antsibull_changelog/config.py, src/antsibull_changelog/fragment.py, src/antsibull_changelog/rendering/__init__.py, src/antsibull_changelog/rendering/_document.py, src/antsibull_changelog/rendering/changelog.py, src/antsibull_changelog/rendering/document.py, src/antsibull_changelog/rendering/markdown.py, src/antsibull_changelog/rendering/md_document.py, src/antsibull_changelog/rendering/rst.py, src/antsibull_changelog/rendering/rst_document.py, src/antsibull_changelog/rendering/utils.py, src/antsibull_changelog/rst.py, tests/functional/test_changelog_archive.py, tests/functional/test_changelog_basic_ansible.py, tests/functional/test_changelog_basic_ansible_classic.py, tests/functional/test_changelog_basic_collection.py, tests/functional/test_changelog_basic_other.py, tests/functional/test_rendering.py, tests/units/test_config.py
This is a project to render changelogs as MarkDown files next to ReStructuredText files (the current default).
This is necessary since GitHub screwed up their RST preview, which results in many collection changelogs to no longer render. This also affects the main Ansible changelogs.
Ref: https://github.com/orgs/community/discussions/86715
=> Support rendering changelog as MarkDown files

changelogs/fragments/151-generate-output-format.yml, src/antsibull_changelog/cli.py, tests/functional/test_changelog_basic_collection.py
=> Fix check for output format

src/antsibull_changelog/changes.py
`ChangesData.sort()` calls `super().sort()`, which is an abstract method and doesn't do anything.
=> Remove bad super call

changelogs/config.yaml, changelogs/fragments/162-add-plugin-period.yaml, docs/changelog-configuration.md, src/antsibull_changelog/cli.py, src/antsibull_changelog/config.py, src/antsibull_changelog/plugins.py, tests/functional/test_changelog_basic_ansible.py, tests/functional/test_changelog_basic_ansible_classic.py, tests/functional/test_changelog_basic_collection.py
=> Add period to end of new plugin statements in changelog

changelogs/config.yaml, changelogs/fragments/160-changelog-nice-yaml.yml, docs/changelog-configuration.md, src/antsibull_changelog/changes.py, src/antsibull_changelog/config.py, src/antsibull_changelog/yaml.py
* Adds yaml boundary marker `---` to the header of the file.
* Increases indentation level on list items.
fixes: #91 
fixes: #152
=> fix: make yaml output pass `ansible-lint`

changelogs/fragments/167-python.yml, src/antsibull_changelog/cli.py, src/antsibull_changelog/constants.py
It was checking for Python 3.6, for which we dropped support quite some time ago (we're requiring Python 3.9+ since 2022-12-17).
=> Remove Python version check

changelogs/fragments/173-argcomplete.yml, src/antsibull_changelog/ansible.py, src/antsibull_changelog/cli.py, src/antsibull_changelog/rstcheck.py, tests/functional/test_changelog_basic_collection.py
Basically [argcomplete](https://pypi.org/project/argcomplete/) support was already partially there, but the marker was missing to easily use it.
This also changes code to only import `ansible` and `rstcheck`/`docutils` when needed; this improves performance a lot (and thus makes tab complete less sluggy). On my machine, running `antsibull-changelog --help` sped up from ~0.6s to ~0.1s.
=> Make CLI startup faster, support tab completion with argcomplete

README.md, docs/community.md, docs/index.md, mkdocs.yml
Dear maintainers,
As a part of the [Consolidating Ansible discussion platforms initiative](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812), this PR adds the communication section template defined by the community to the README and the docsite. Similar PRs are now being raised across all the Ansible ecosystem projects.
Thank you
=> Docsite: add Community guide

changelogs/fragments/182-strict-linting.yml, docs/changelog.yaml-format.md, noxfile.py, src/antsibull_changelog/cli.py, src/antsibull_changelog/lint.py, tests/functional/bad/ansible-base-1.json, tests/functional/bad/felixfontein.hosttech_dns-1.json, tests/functional/bad/random-1.json, tests/functional/bad/random-2.json, tests/functional/bad/random-3.json, tests/functional/bad/random-4.json, tests/functional/bad/random-4.yaml, tests/functional/test_changelog_yaml_linter.py
The extra check makes sure that nothing's there that shouldn't be in changelogs/changelog.yaml.
=> Add --strict parameter to lint-changelog-yaml subcommand

changelogs/fragments/185-core-modules.yml, src/antsibull_changelog/plugins.py
=> Fix namespace extraction for ansible-core modules

changelogs/fragments/188-rstcheck.yml, src/antsibull_changelog/fragment.py, tests/functional/test_changelog_basic_lint.py
Right now only the second letter of a rstcheck warning/error is printed.
=> Fix shredding errors/warnings reported by rstcheck

changelogs/fragments/193-config.yml, pyproject.toml, src/antsibull_changelog/cli.py, src/antsibull_changelog/config.py, tests/units/test_config.py
To prepare https://github.com/ansible-community/antsibull-changelog/issues/190#issuecomment-2628377419, I'd like to use pydantic to validate the config. This would also allow to add a config validator (~~which I'll likely do in this PR as well~~).
=> Switch to pydantic for config parsing and validation

changelogs/fragments/196-lint-strict.yml, docs/changelog.yaml-format.md, noxfile.py, src/antsibull_changelog/cli.py
The integration tests never ran anything, since `antsibull.cli` did not have an `if __name__ == "__main__"`...
Also `antsibull-changelog lint-changelog-yaml`'s `--strict` parameter requires a `true`/`false` (or `yes`/`no`) value.
Ref: #195.
=> Fix integration tests; make --strict a proper flag
