ansible-community/antsibull-changelog

docs/changelogs.rst

hoping I got the list right :-)

add list of categories for porting guide

---

docs/changelogs.rst

Improve docs

---

CHANGELOG.rst
antsibull_changelog/plugins.py
docs/changelogs.rst
tests/functional/test_changelog_basic_ansible.py
tests/functional/test_changelog_basic_ansible_classic.py
tests/functional/test_changelog_basic_collection.py

Fix wrongly detected module namespaces in presence of symlinks

---

CHANGELOG.rst
antsibull_changelog/changelog_generator.py

Needed for ansible-community/antsibull#103.

Make changelog generator code more flexible

---

CHANGELOG.rst
antsibull_changelog/changes.py
antsibull_changelog/config.py
antsibull_changelog/fragment.py
docs/changelogs.rst

Add archive functionality when keep_fragments is set to false

---

antsibull_changelog/changes.py
antsibull_changelog/cli.py
antsibull_changelog/config.py
antsibull_changelog/fragment.py
docs/changelogs.rst
tests/functional/fixtures.py
tests/functional/test_changelog_archive.py
tests/functional/test_changelog_basic_collection.py
tests/units/test_config.py

Improve refresh

---

CHANGELOG.rst
antsibull_changelog/changes.py
tests/functional/good/felixfontein.versioning_test_collection-1.yaml
tests/functional/test_changelog_basic_collection.py
tests/functional/test_changelog_basic_lint.py

Do not crash when generating changelog which contains the trivial section

---

CHANGELOG.rst
antsibull_changelog/changes.py
antsibull_changelog/config.py
docs/changelog-configuration.rst
tests/functional/test_changelog_archive.py

Fixes #46. With the option it is possible to restore the old behavior, if someone really wants it.

Add prevent_known_fragments option

---

CHANGELOG.rst
antsibull_changelog/changes.py
antsibull_changelog/cli.py

Needed to prevent https://github.com/ansible-collections/community.general/issues/1933.

Add --cummulative-release option

---

CHANGELOG.rst
antsibull_changelog/changes.py

Add warning when release_summary is missing

---

codecov.yml
tests/functional/fixtures.py
tests/functional/test_changelog_basic_ansible.py
tests/functional/test_changelog_basic_ansible_classic.py
tests/functional/test_changelog_basic_collection.py

More parts of #55 that are independent.

Improve tests

---

docs/changelog.yaml-format.md

`known_issues` was missing in the changelog format specification.

Synchronize / improve changelog docs

---

docs/changelog.yaml-format.md
docs/changelogs.rst

See also https://github.com/ansible/ansible/pull/77871.

Document new plugins/objects and when they are available

---

src/antsibull_changelog/cli.py

`pip install toml` installs `tomli`...

Also support tomli

---

docs/changelog.yaml-format.md

Signed-off-by: gardar <gardar@users.noreply.github.com>

docs: fix changelog filename typo

---

.github/workflows/pythontests.yml
changelogs/fragments/101-tomllib.yml
pyproject.toml
src/antsibull_changelog/cli.py
src/antsibull_changelog/toml.py
stubs/tomllib.pyi
tests/functional/fixtures.py
tests/functional/test_changelog_basic_other.py

Support Python 3.11's tomllib as well

---

README.md
noxfile.py

This got forgotten during the linting step.

Lint changelog fragments

---

.pre-commit-hooks.yaml
changelogs/fragments/125-pre-commit-hook.yaml

/cc @jooola
Closes: https://github.com/ansible-community/antsibull-changelog/issues/124

Add pre-commit.com hooks for lint subcommands

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0.22.0.yml
changelogs/fragments/125-pre-commit-hook.yaml
changelogs/fragments/126-toml-extra.yaml
pyproject.toml

- Prepare 0.22.0 release
- Release 0.22.0.

Release 0.22.0

---

changelogs/fragments/130-generate-version.yml
src/antsibull_changelog/changes.py
src/antsibull_changelog/cli.py
tests/functional/test_changelog_basic_collection.py

Allow to generate changelog for a specific version

---

src/antsibull_changelog/cli.py

This fixes currently broken CI.

Remove unnecessary pyre-ignore

---

.github/workflows/nox.yml
noxfile.py

Ref: https://github.com/ansible-community/antsibull-docs/pull/256

nox CI: Use matrix, set up environments separately from running tests

---

README.md
docs/index.md

Ref: https://github.com/ansible-community/antsibull-core/issues/146

Reference #antsibull:ansible.com Matrix room

---

docs/changelog-configuration.md

Ref: https://github.com/ansible-community/antsibull-changelog/pull/160#discussion_r1613977478

Config docs: fix note, order alphabetically

---

changelogs/fragments/166-use-constants.yml
src/antsibull_changelog/cli.py
src/antsibull_changelog/constants.py
tests/functional/test_changelog_archive.py
tests/functional/test_changelog_basic_ansible.py
tests/functional/test_changelog_basic_ansible_classic.py
tests/functional/test_changelog_basic_collection.py
tests/functional/test_changelog_basic_lint.py
tests/functional/test_changelog_basic_other.py

Create and use constants for return codes

---

tests/functional/test_changelog_basic_ansible.py
tests/functional/test_changelog_basic_collection.py
tests/functional/test_changelog_reformat.py
tests/functional/test_changelog_yaml_linter.py

Use some more RC constants

---

README.md
changelogs/fragments/171-pyre.yml
noxfile.py
pyproject.toml
src/antsibull_changelog/rendering/markdown.py
src/antsibull_changelog/rendering/utils.py

Let's get rid of it; mypy should be enough.

Remove pyre

---

changelogs/fragments/181-extra-data.yml
src/antsibull_changelog/changes.py
src/antsibull_changelog/lint.py

Adds basic callbacks which can be used to extract, re-add, and remove/lint extra data.
Ref: https://github.com/ansible-community/ansible-build-data/pull/478#issuecomment-2408451508

Allow to handle extra data while loading, saving, and linting

---

changelogs/config.yaml
changelogs/fragments/194-output.yml
docs/changelog-configuration.md
docs/changelog.md
docs/changelog.md.license
noxfile.py
pyproject.toml
src/antsibull_changelog/changelog_generator.py
src/antsibull_changelog/cli.py
src/antsibull_changelog/config.py
src/antsibull_changelog/rendering/changelog.py
tests/functional/fixtures.py
tests/functional/test_changelog_archive.py
tests/functional/test_changelog_basic_collection.py
tests/functional/test_changelog_basic_other.py
tests/units/test_config.py

See https://github.com/ansible-community/antsibull-changelog/issues/190#issuecomment-2628377419 for details.
Fixes #190
Closes #191

Add `output` setting to better control which files are written and how they are formatted

---

changelogs/fragments/199-deprecate-boolean-valued-flags.yml

Announce deprecation of boolean valued options

---

changelogs/fragments/203-section-underline.yml
src/antsibull_changelog/rendering/rst_document.py

Needed to fix the Ansible 12 porting guide.

Allow to configure section underlines
